FItnessTrack/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FItnessTrack.Models
{
    public class Cart
    {
        public int CartId { get; set; } //PK

        public int ServiceId { get; set; }

        public DateTime DateCreated { get; set; }

        public int Quantity { get; set; }

        public double Charge { get; set; }
        public string CustomerId { get; set; }
        public Service Service { get; set; }
    }
}

FItnessTrack/Controllers/API/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FItnessTrack.Data;
using FItnessTrack.Models;

namespace FItnessTrack.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class CartsController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public CartsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/Carts
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Cart>>> GetCarts()
        {
            return await _context.Carts.ToListAsync();
        }

        // GET: api/Carts/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Cart>> GetCart(int id)
        {
            var cart = await _context.Carts.FindAsync(id);

            if (cart == null)
            {
                return NotFound();
            }

            return cart;
        }

        // PUT: api/Carts/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPut("{id}")]
        public async Task<IActionResult> PutCart(int id, Cart cart)
        {
            if (id != cart.CartId)
            {
                return BadRequest();
            }

            _context.Entry(cart).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CartExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Carts
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPost]
        public async Task<ActionResult<Cart>> PostCart(Cart cart)
        {
            _context.Carts.Add(cart);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetCart", new { id = cart.CartId }, cart);
        }

        // DELETE: api/Carts/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<Cart>> DeleteCart(int id)
        {
            var cart = await _context.Carts.FindAsync(id);
            if (cart == null)
            {
                return NotFound();
            }

            _context.Carts.Remove(cart);
            await _context.SaveChangesAsync();

            return cart;
        }

        private bool CartExists(int id)
        {
            return _context.Carts.Any(e => e.CartId == id);
        }
    }
}

FItnessTrack/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FItnessTrack.Data;
using FItnessTrack.Models;
using Microsoft.AspNetCore.Authorization;

namespace FItnessTrack.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ServicesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ServicesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Services
        public async Task<IActionResult> Index()
        {
            return View(await _context.Services.ToListAsync());
        }

        // GET: Services/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = await _context.Services
                .FirstOrDefaultAsync(m => m.ServiceId == id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        // GET: Services/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Services/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ServiceId,ServiceName,FirstName,LastName")] Service service)
        {
            if (ModelState.IsValid)
            {
                _context.Add(service);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(service);
        }

        // GET: Services/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = await _context.Services.FindAsync(id);
            if (service == null)
            {
                return NotFound();
            }
            return View(service);
        }

        // POST: Services/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ServiceId,ServiceName,FirstName,LastName")] Service service)
        {
            if (id != service.ServiceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(service);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServiceExists(service.ServiceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(service);
        }

        // GET: Services/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var service = await _context.Services
                .FirstOrDefaultAsync(m => m.ServiceId == id);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var service = await _context.Services.FindAsync(id);
            _context.Services.Remove(service);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServiceExists(int id)
        {
            return _context.Services.Any(e => e.ServiceId == id);
        }
    }
}

FItnessTrack/Controllers/ShopController.cs
using FItnessTrack.Data;
using FItnessTrack.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Stripe;
using System.Configuration; // Read the Strip API keys from appssettings.json
using Microsoft.Extensions.Configuration;
using Stripe.Checkout;

namespace FItnessTrack.Controllers
{
    public class ShopController : Controller
    {
        private readonly ApplicationDbContext _context;

        private IConfiguration _iconfiguation;

        public ShopController(ApplicationDbContext context, IConfiguration iconfiguation)
        {
            _context = context;
            _iconfiguation = iconfiguation;
        }
        public IActionResult Index()
        {
            //Get a list of categories to display to customers on the main shopping page
            var Services = _context.Services.OrderBy(c => c.ServiceName).ToList();
            return View(Services);
        }
        public IActionResult Browse(int id)
        {
            // query Products for the selected Category
            var products = _context.Trainings.Where(p => p.ServiceId == id).OrderBy(p => p.Desciption).ToList();

            // get Name of selected Category.  Find() only filters on key fields
            ViewBag.category = _context.Services.Find(id).ServiceName.ToString();
            return View(products);
        }
        public IActionResult AddToCart(int ServiceId, int Quantity)
        {
            var price = _context.Services.Find(ServiceId).Charge;

            var currentDateTime = DateTime.Now;

            var CustomerId = GetCustomerId();

            var cart = new Cart
            {
                ServiceId = ServiceId,
                Quantity = Quantity,
                Charge = price,
                DateCreated = currentDateTime,
                CustomerId = CustomerId   
            };

            _context.Carts.Add(cart);
            _context.SaveChanges();

            return RedirectToAction("Cart");
        }

        private string GetCustomerId()
        {
            // check the session for an existing CustomerId
            if (HttpContext.Session.GetString("CustomerId") == null)
            {
                // if we don't already have an existing CustomerId in the session, check if customer is logged in
                var CustomerId = "";

                // if customer is logged in, use their email as the CustomerId
                if (User.Identity.IsAuthenticated)
                {
                    CustomerId = User.Identity.Name; //Name = email address
                }
                // if the customer is anonymous, use Guid to create a new identifier
                else
                {
                    CustomerId = Guid.NewGuid().ToString();
                }
                // now store the CustomerId in a session variable
                HttpContext.Session.SetString("CustomerId", CustomerId);
            }
            // return the Session variable
            return HttpContext.Session.GetString("CustomerId");
        }


        public IActionResult Cart()
        {
            // fetch current cart for display
            var CustomerId = "";
            // in case user comes to cart page before adding anything, identify them first
            if (HttpContext.Session.GetString("CustomerId") == null)
            {
                CustomerId = GetCustomerId();
            }
            else
            {
                CustomerId = HttpContext.Session.GetString("CustomerId");
            }

            // query the db for this customer
            //Add the "Include(c => c.Product)" to have our query include the Parent Products into our cart
            var cartItems = _context.Carts.Include(c => c.Service).Where(c => c.CustomerId == CustomerId).ToList();

            // pass the data to the view for display
            return View(cartItems);
        }

        //GET /Shop/RemoveFromCart
        public IActionResult RemoveFromCart(int id)
        {
            // find the item with this PK value
            var cartItem = _context.Carts.Find(id);

            // delete record from Carts table
            if (cartItem != null)
            {
                _context.Carts.Remove(cartItem);
                _context.SaveChanges();
            }

            //redirect to updated Cart
            return RedirectToAction("Cart");
        }

        [Authorize]

        public IActionResult Checkout()
        {
            return View();
        }

        //POST: /Shop/Checkout
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([Bind("FirstName, LastName, Address, City, Province, PostalCode")] Models.Order order)
        {
            //Populate the 3 automatic Order properties
            order.OrderDate = DateTime.Now;
            order.CustomerId = User.Identity.Name;
            //calc order total based on the current cart
            order.Total = (from c in _context.Carts
                           where c.CustomerId == HttpContext.Session.GetString("CustomerId")
                           select c.Quantity * c.Charge).Sum();

            //use SessionExtension Obj to store the order Obj in a session variable
            HttpContext.Session.SetObject("Order", order);

            //redirect to Payment Page
            return RedirectToAction("Payment");
        }

        [Authorize]
        public IActionResult Payment()
        {
            var order = HttpContext.Session.GetObject<Models.Order>("Order");

            ViewBag.Total = order.Total;

            // also use the ViewBag to set the PublishableKey, which we can read from the Configuration
            ViewBag.PublishableKey = _iconfiguation.GetSection("Stripe")["PublishableKey"];

            // load the Payment view
            return View();
        }

        //POST /Shop/ProcessPayment
        [Authorize]
        [HttpPost]
        public IActionResult ProcessPayment()
        {
            var order = HttpContext.Session.GetObject<Models.Order>("Order");
            // get the Stripe Secret Key from the configuration and pass it before we can create a new checkout session
            StripeConfiguration.ApiKey = _iconfiguation.GetSection("Stripe")["SecretKey"];

            // code will go here to create and submit Stripe payment charge
            var options = new SessionCreateOptions
            {
                PaymentMethodTypes = new List<string>
                {
                  "card",
                },
                LineItems = new List<SessionLineItemOptions>
                {
                  new SessionLineItemOptions
                  {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                      UnitAmount = (long?)order.Total,
                      Currency = "cad",
                      ProductData = new SessionLineItemPriceDataProductDataOptions
                      {
                        Name = "Fitness Track Purchase",
                      },
                    },
                    Quantity = 1,
                  },
                },
                Mode = "payment",
                SuccessUrl = "https://" + Request.Host + "/Shop/SaveOrder",
                CancelUrl = "https://" + Request.Host + "/Shop/Cart"
            };
            var service = new SessionService();
            Session session = service.Create(options);
            return Json(new { id = session.Id });
        }
        // GET: /Shop/SaveOrder
        [Authorize]
        public IActionResult SaveOrder()
        {
            // get the order from the session variable
            var order = HttpContext.Session.GetObject<Models.Order>("Order");
            // save as new order to the db
            _context.Orders.Add(order);
            _context.SaveChanges();

            // save the line items as new order details records
            var cartItems = _context.Carts.Where(c => c.CustomerId == HttpContext.Session.GetString("CustomerId"));
            foreach (var item in cartItems)
            {
                var orderDetail = new OrderDetail
                {
                    ServiceId = item.ServiceId,
                    Quantity = item.Quantity,
                    Charge = item.Charge,
                    OrderId = order.OrderId
                };

                _context.OrderDetails.Add(orderDetail);
            }
            _context.SaveChanges();

            // delete the items from the user's cart
            foreach (var item in cartItems)
            {
                _context.Carts.Remove(item);
            }
            _context.SaveChanges();

            // set the Session ItemCount variable (which shows in the navbar) back to zero
            HttpContext.Session.SetInt32("ItemCount", 0);

            // redirect to order confirmation page i.e. /Orders/Details/1
            return RedirectToAction("Details", "Orders", new { @id = order.OrderId });
        }
    }
}

FItnessTrack/Views/Shop/Browse.cshtml
@model IEnumerable<FItnessTrack.Models.PersonalTraining>

<h1>Feel Free to Browse our Sevices</h1>

<h3 style="color:navajowhite">Selected service: @ViewBag.category</h3>


<section>
    <div class="row">

        @foreach (var item in Model)
        {
        <div class="col-sm-6 col-lg-4 mb-3">
            <div class="card mb-3 text-center h-100">
                <div class="card-header-tabs">
                    <h6> <a asp-controller="Services" asp-action="Details" asp-route-id="@item.ServiceId">Charge: @item.Charge</a> </h6>
                    <p style="color:black">
                        @String.Format(item.Desciption)
                    </p>

                    <form method="post" action="/Shop/AddToCart">
                        <!--Hidden Field forhte selected produict id-->
                        <input type="hidden" id="ServiceId" name="ServiceId" value="@item.ServiceId" />
                        <div class="form-group">
                            <label style="color:#41ADFF" control-label" for="Quantity">Quantity: </label>
                            <input name="Quantity" id="Quantity" required min="1" max="99999" type="number" class="input-small" />
                        </div>
                        <style>
                            .input-small {
                                width: 60px;
                                height: 30px;
                                margin-left: 95px;
                            }

                            .btn-primary {
                                margin-left: 10px;
                            }
                        </style>
                        <button class="btn btn-primary">Add To Cart</button>
                    </form>
                </div>
            </div>
        </div>}
            </div>
</section>

FItnessTrack/Views/Shop/Cart.cshtml
@model IEnumerable<FItnessTrack.Models.Cart>

@{
    ViewData["Title"] = "Your Cart";
    Layout = "~/Views/Shared/_Layout.cshtml";
    double total = 0;
}

<h1>Your Cart</h1>

<table class="table table-striped" style="color:whitesmoke">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Service)
            </th>
            <th class="text-right">
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Charge)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            total += (item.Quantity * item.Charge);
            <tr>
                <td>
                    <a asp-controller="PersonalTrainings" asp-action="Details" asp-route-id="@item.ServiceId">@item.Service.ServiceName</a>

                    @*@Html.DisplayFor(modelItem => item.Service.ServiceName)*@
                </td>
                <td class="text-right">
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @String.Format("{0:c}", item.Charge)
                </td>
                <td>
                    <a asp-action="RemoveFromCart" asp-route-id="@item.CartId">Delete</a>
                </td>
            </tr>
        }
        <tr>
            <td colspan="4" class="text-md-center" style="white-space:initial">
                @String.Format("Total: {0:c} ", total)
            </td>
            <td>
                <a class="btn btn-primary align-content-lg-around " asp-action="Index">Keep Shop</a>
                <a class="btn btn-primary align-content-lg-end" asp-action="Checkout">Check-Out</a>
            </td>
            <style>

                .align-content-lg-end {
                    margin-left: -210px;
                }

                .align-content-lg-around {
                    margin-left: -125px;
                }

                .text-md-center {
                    color: aquamarine;
                }
            </style>
        </tr>
    </tbody>
</table>

FItnessTrack/Views/Shop/Checkout.cshtml
@model FItnessTrack.Models.Order

@{
    ViewData["Title"] = "Checkout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1> Checkout here! </h1>

    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Checkout">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="FirstName" class="control-label"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="control-label"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label"></label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"required></span>
                </div>
                <div class="form-group">
                    <label asp-for="City" class="control-label"></label>
                    <input asp-for="City" class="form-control" />
                    <span asp-validation-for="City" class="text-danger"required></span>
                </div>
                <div class="form-group">
                    <label asp-for="Province" class="control-label"></label>
                    <input asp-for="Province" class="form-control" />
                    <span asp-validation-for="Province" class="text-danger"required></span>
                </div>
                <div class="form-group">
                    <label asp-for="PostalCode" class="control-label"></label>
                    <input asp-for="PostalCode" class="form-control" />
                    <span asp-validation-for="PostalCode" class="text-danger"required></span>
                </div>
                <div class="form-group">
                    <label asp-for="Phone" class="control-label"></label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                
                <div class="form-group">
                    <input type="submit" value="Payment >>" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

FItnessTrack/Views/Shop/Index.cshtml
@model IEnumerable<FItnessTrack.Models.Service>

@{
    ViewData["Title"] = "Have a Look for your body's fitness";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Choose Our Service!</h1>
<section>
    <div class="row">

        @foreach (var item in Model)
        {
            <div class="col-sm-6 col-lg-4 mb-3">
                <div class="card mb-3 text-center h-100">
                    <div class="card-header-tabs">
                        <a asp-controller="Shop" asp-action="Browse" asp-route-id="@item.ServiceId"> @item.ServiceName</a>
                    </div>
                </div>
            </div>
        }
    </div>
</section>

FItnessTrack/Views/Shop/Payment.cshtml
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
<script src="https://js.stripe.com/v3/"></script>


<section>
    <div class="product">

        <div class="description">
            <h3>Your Order Total</h3>
            <h5>@String.Format("{0:c}", ViewBag.Total)</h5>
        </div>
    </div>
    <button id="checkout-button" class="btn btn-primary">Continue to Payment >></button>
</section>

<script type="text/javascript">
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe("@ViewBag.PublishableKey");
    var checkoutButton = document.getElementById("checkout-button");
    checkoutButton.addEventListener("click", function () {
        fetch("/Shop/ProcessPayment", {
            method: "POST",
        })
            .then(function (response) {
                return response.json();
            })
            .then(function (session) {
                return stripe.redirectToCheckout({ sessionId: session.id });
            })
            .then(function (result) {
                // If redirectToCheckout fails due to a browser or network
                // error, you should display the localized error message to your
                // customer using error.message.
                if (result.error) {
                    alert(result.error.message);
                }
            })
            .catch(function (error) {
                console.error("Error:", error);
            });
    });
</script>